version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - apupier
  - lhein
  - bfitzpat
  ignore:
  - dependency-name: atom-languageclient
    versions:
    - 1.1.1
    - 1.2.0
    - 1.2.1
    - 1.4.0
    - 1.7.0
    - 1.8.2
